--- #YAML:1.0
name:                Sepia
version:             0.66
abstract:            Simple Emacs-Perl InterAction
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    B::Module::Info:               0
    Data::Dumper:                  0
    PadWalker:                     0
    Scalar::Util:                  0
    Sub::Uplevel:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Sean O'Rourke <seano@cpan.org>
